In [34]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [35]:
#load Dataset
df = pd.read_csv("bookstore_customers_expanded.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          12000 non-null  int64
 1   signup_date          12000 non-null  object
 2   home_store           12000 non-null  object
 3   annual_visits        12000 non-null  int64
 4   online_ratio         12000 non-null  float64
 5   ltv_estimate         12000 non-null  float64
 6   first_purchase_date  12000 non-null  object
 7   last_purchase_date   12000 non-null  object
 8   region               12000 non-null  object
 9   loyalty_member       12000 non-null  bool
 10  total_purchases      12000 non-null  int64
 11  total_spent          12000 non-null  float64
 12  avg_purchase_value   12000 non-null  float64
 13  visits_2023          12000 non-null  int64
 14  has_escalation       12000 non-null  bool
 15  escalation_reason    2854 non-null   object
 16  customer_rating      12000 non-null  float64
dtypes: bool(2), float64(5), int64(4), object(6)
memory usage: 1.4+ MB

In [36]:
df.head(10)

,customer_id,signup_date,home_store,annual_visits,online_ratio,ltv_estimate,first_purchase_date,last_purchase_date,region,loyalty_member,total_purchases,total_spent,avg_purchase_value,visits_2023,has_escalation,escalation_reason,customer_rating
0,1,2019-06-08,YYC-NW,18,0.25,62.70,2019-06-08,2019-11-22,Calgary NW,False,84,6117.54,72.83,19,True,Rude Staff,3.95
1,2,2023-12-21,YYC-NW,9,0.47,40.67,2023-12-21,2024-12-16,Calgary NW,False,10,540.63,54.06,10,True,Damaged Book,3.08
2,3,2021-03-10,ONLINE,3,0.25,220.50,2021-03-10,2022-01-10,Online,False,9,616.40,68.49,3,False,NaN,4.38
3,4,2021-08-13,ONLINE,15,0.43,466.80,2021-08-13,2023-11-03,Online,False,48,2125.24,44.28,14,True,Late Delivery,3.53
4,5,2024-02-12,YYC-NW,2,0.25,179.24,2024-02-12,2024-09-01,Calgary NW,False,1,36.92,36.92,1,False,NaN,3.41
5,6,2024-04-18,YYC-NW,8,0.26,115.90,2024-04-18,2024-10-16,Calgary NW,False,5,214.42,42.88,8,True,Rude Staff,4.13
6,7,2019-11-17,YYC-SE,18,0.18,266.92,2019-11-17,2022-03-16,Calgary SE,False,73,1843.39,25.25,15,True,Damaged Book,3.51
7,8,2019-06-23,YYC-NW,5,0.20,355.06,2019-06-23,2022-10-27,Calgary NW,False,24,695.07,28.96,4,False,NaN,3.88
8,9,2021-03-22,YYC-NW,15,0.34,142.81,2021-03-22,2022-06-07,Calgary NW,False,43,2937.53,68.31,9,True,Damaged Book,3.71
9,10,2020-02-17,YYC-DT,14,0.20,150.97,2020-02-17,2021-12-12,Calgary Downtown,False,56,4013.58,71.67,16,True,Website Issue,3.98

In [37]:
#Mengganti data NULL/NAN dengan keterangan
df['escalation_reason']= df['escalation_reason'].fillna('No Description')

In [38]:
# Jumlah Customer berdasarkan ID unik, supaya tidak duplikat
display (f"Total customer : {df['customer_id'].nunique()}")

#rata-rata total spent
display(f'Average of Total Spent: {df['total_spent'].mean()}')

#rata-rata anual visits
display(f'Average of Annual Visits : {df['annual_visits'].mean()}')

# rata-rata online ratio
display(f'Average of Online Ration : {df['online_ratio'].mean()}')

# rata rata ltv
display(f'Average of ltv : {df['ltv_estimate'].mean()}')

# distribusi ratting
display(f'Average of Customer Rating : {df['customer_rating'].mean()}')

'Total customer : 12000'

'Average of Total Spent: 1680.0957625'

'Average of Annual Visits : 10.449916666666667'

'Average of Online Ration : 0.2860391666666667'

'Average of ltv : 150.03188083333333'

'Average of Customer Rating : 3.967115833333333'

In [39]:
# Toko teratas berdasarkan jumlah customer
df['home_store'].value_counts()

home_store
YYC-DT    4731
YYC-NW    3375
YYC-SE    2645
ONLINE    1249
Name: count, dtype: int64

In [40]:
# Region customer teratas
df['region'].value_counts()

region
Calgary Downtown    4731
Calgary NW          3375
Calgary SE          2645
Online              1249
Name: count, dtype: int64

In [41]:
#Melihat dominasi customer online
online_dom = (df['online_ratio'] > 0.5).mean() * 100
online_dom

np.float64(10.625)

In [42]:
#Melihat dominasi customer offline
offline_dom = (df['online_ratio'] < 0.5).mean() * 100
offline_dom

np.float64(88.46666666666667)

In [43]:
#Melihat dominasi customer hybrid (online dan offline)
Balanced = (df['online_ratio'] == 0.5).mean() * 100
Balanced

np.float64(0.9083333333333334)

In [44]:
# menyatukan dalam bentuk dataframe dictionary
pd.DataFrame({
    'Category': ['Online-Dominant', 'Offline-Dominant', 'Balanced'],
    'Percentage': [round(online_dom, 2), round(offline_dom, 2), round(Balanced, 2)]
})

           Category  Percentage
0   Online-Dominant       10.62
1  Offline-Dominant       88.47
2          Balanced        0.91

In [45]:
# jumlah pengguna loyalty vs non
df['loyalty_member'].value_counts()

loyalty_member
False    9652
True     2348
Name: count, dtype: int64

In [46]:
# persentase perbandingan pengguna loyalty dan non
percentage = df['loyalty_member'].value_counts(normalize=True) * 100
round(percentage, 2)

loyalty_member
False    80.43
True     19.57
Name: proportion, dtype: float64

In [47]:
#Rata rata kunjungan tahun 2023
df['visits_2023'].mean()

np.float64(8.84675)

In [48]:
#Jumlah kunjungan tahun 2023
df['visits_2023'].sum()

np.int64(106161)

In [49]:
df['visits_2023'].describe()

count    12000.000000
mean         8.846750
std          4.994898
min          1.000000
25%          5.000000
50%          8.000000
75%         12.000000
max         23.000000
Name: visits_2023, dtype: float64

In [50]:
#Pelabelan/klasifikasi berdasarkan jumlah kunjungan
df['visit_category'] = pd.cut(
    df['visits_2023'],
    bins=[0, 2, 6, 20, 100],
    labels=['Sangat Jarang', 'Jarang', 'Sering', 'Sangat Sering']
)

df['visit_category'].value_counts()

visit_category
Sering           7392
Jarang           3275
Sangat Jarang    1175
Sangat Sering     158
Name: count, dtype: int64

In [51]:
# top customer yang merupakan spender tertinggi
top10_spenders = df.nlargest(10, 'total_spent')[['customer_id','total_spent','total_purchases','home_store','region']]
display(top10_spenders)

       customer_id  total_spent  total_purchases home_store            region
6092          6093      9840.73              114     YYC-NW        Calgary NW
9535          9536      9705.35              117     YYC-NW        Calgary NW
6465          6466      9693.24              104     YYC-DT  Calgary Downtown
2720          2721      9648.26              118     YYC-SE        Calgary SE
8915          8916      9465.96              115     YYC-NW        Calgary NW
10542        10543      9444.90              110     YYC-DT  Calgary Downtown
2676          2677      9444.87              112     YYC-SE        Calgary SE
2765          2766      9313.77              105     YYC-DT  Calgary Downtown
9861          9862      9093.42              100     YYC-DT  Calgary Downtown
11909        11910      8922.14               97     YYC-DT  Calgary Downtown

In [52]:
#Ringkasan statistik
df['total_spent'].describe()        # summary stats

count    12000.000000
mean      1680.095763
std       1595.744960
min          0.000000
25%        472.087500
50%       1168.945000
75%       2414.372500
max       9840.730000
Name: total_spent, dtype: float64

In [53]:
# untuk melihat distribusi kasar
spending_bins = pd.cut(df['total_spent'], bins=[-1,50,100,250,500,1000,5000, np.inf])
df.groupby(spending_bins, observed=False)['customer_id'].count()

total_spent
(-1.0, 50.0]         216
(50.0, 100.0]        346
(100.0, 250.0]      1059
(250.0, 500.0]      1529
(500.0, 1000.0]     2271
(1000.0, 5000.0]    5984
(5000.0, inf]        595
Name: customer_id, dtype: int64

In [54]:
#Rata Rata pengeluaran pelanggan
avg_spent_by_region = df.groupby('region')['total_spent'].mean().sort_values(ascending=False)
display(avg_spent_by_region)

region
Calgary SE          1713.843660
Calgary Downtown    1686.516016
Calgary NW          1661.117316
Online              1635.592042
Name: total_spent, dtype: float64

In [55]:
#Rata-rata pengeluaran loyalty member vs non loyalty
avg_spent_loyalty = df.groupby('loyalty_member')['total_spent'].agg(['count','mean','median']).reset_index()
display(avg_spent_loyalty)

   loyalty_member  count         mean    median
0           False   9652  1670.427075  1164.250
1            True   2348  1719.841150  1184.245

In [56]:
# korelasi online_ratio, total_spent, annual_visits

for col in ['online_ratio','total_spent','annual_visits','total_purchases','customer_rating']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Pearson correlations
corr_online_total = df['online_ratio'].corr(df['total_spent'])
corr_visits_purchases = df['annual_visits'].corr(df['total_purchases'])
corr_rating_spent = df['customer_rating'].corr(df['total_spent'])

corrs = {
    'online_ratio_vs_total_spent': corr_online_total,
    'annual_visits_vs_total_purchases': corr_visits_purchases,
    'customer_rating_vs_total_spent': corr_rating_spent
}
corrs_df = pd.DataFrame({
    'Metric': [
        'Online Ratio vs Total Spent',
        'Annual Visits vs Total Purchases',
        'Customer Rating vs Total Spent'
    ],
    'Correlation': [
        corr_online_total,
        corr_visits_purchases,
        corr_rating_spent
    ]
})

corrs_df

                             Metric  Correlation
0       Online Ratio vs Total Spent    -0.007201
1  Annual Visits vs Total Purchases     0.603287
2    Customer Rating vs Total Spent     0.011447

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          12000 non-null  int64
 1   signup_date          12000 non-null  object
 2   home_store           12000 non-null  object
 3   annual_visits        12000 non-null  int64
 4   online_ratio         12000 non-null  float64
 5   ltv_estimate         12000 non-null  float64
 6   first_purchase_date  12000 non-null  object
 7   last_purchase_date   12000 non-null  object
 8   region               12000 non-null  object
 9   loyalty_member       12000 non-null  bool
 10  total_purchases      12000 non-null  int64
 11  total_spent          12000 non-null  float64
 12  avg_purchase_value   12000 non-null  float64
 13  visits_2023          12000 non-null  int64
 14  has_escalation       12000 non-null  bool
 15  escalation_reason    12000 non-null  object
 16  customer_rating      12000 non-null  float64
 17  visit_category       12000 non-null  category
dtypes: bool(2), category(1), float64(5), int64(4), object(6)
memory usage: 1.4+ MB

In [58]:
# karena kolom last_purchase_date dan first_purchase_date masih bertipe object maka ubah ke datetime

df['last_purchase_date'] = pd.to_datetime(df['last_purchase_date'], errors='coerce')
df['first_purchase_date'] = pd.to_datetime(df['first_purchase_date'], errors='coerce')

In [59]:
# customer aktif transaksi dalam 90 hari terakhir
today = df['last_purchase_date'].max()
active_90_mask = (today - df['last_purchase_date']).dt.days <= 90
active_90_count = active_90_mask.sum()
active_90_pct = active_90_mask.mean() * 100
active_90_count, active_90_pct

(np.int64(2045), np.float64(17.041666666666664))

In [60]:
# Menghitung Jumlah Customer Dorman(tidak bertransaksi lebih dari 365 hari terakhir)
dormant_mask = (today - df['last_purchase_date']).dt.days > 365
dormant_count = dormant_mask.sum()
dormant_pct = dormant_mask.mean() * 100
dormant_count, dormant_pct

(np.int64(5973), np.float64(49.775000000000006))

In [61]:
#melihat jumlah kunjungan 90 hari terakhir
df['recency_days'] = (today - df['last_purchase_date']).dt.days
df['lifetime_days'] = (df['last_purchase_date'] - df['first_purchase_date']).dt.days
df[['recency_days','lifetime_days']].describe()

       recency_days  lifetime_days
count  12000.000000   12000.000000
mean     512.336917     583.908500
std      456.339588     475.259934
min        0.000000    -336.000000
25%      142.000000     211.000000
50%      363.500000     452.000000
75%      776.000000     873.000000
max     2087.000000    2149.000000

In [62]:
# Melihat jumlah customer yang pernah komplain
escalation_counts = df['has_escalation'].value_counts()
escalation_pct = df['has_escalation'].value_counts(normalize=True) * 100
escalation_counts, escalation_pct

(has_escalation
 False    9146
 True     2854
 Name: count, dtype: int64,
 has_escalation
 False    76.216667
 True     23.783333
 Name: proportion, dtype: float64)

In [63]:
# Alasan Complain Teratas
top_escalation_reasons = df.loc[df['has_escalation']==True, 'escalation_reason'].value_counts().head(10)
display(top_escalation_reasons)

escalation_reason
Damaged Book     594
Late Delivery    590
Billing Error    576
Website Issue    570
Rude Staff       524
Name: count, dtype: int64

In [64]:
# Melihat Dampak komplain terhadap total_spent, customer_rating, loyalty_member

impact = df.groupby('has_escalation').agg({
    'total_spent': ['count','mean','median'],
    'customer_rating': ['mean','median'],
    'loyalty_member': lambda x: x.mean()  # proporsi yang loyal
})
# beri nama kolom yang rapi
impact.columns = ['_'.join(col).strip() for col in impact.columns.values]
display(impact)

,total_spent_count,total_spent_mean,total_spent_median,customer_rating_mean,customer_rating_median,loyalty_member_<lambda>
has_escalation,,,,,,
False,9146,1702.067317,1183.515,4.108436,4.09,0.216488
True,2854,1609.685168,1119.035,3.514236,3.50,0.128942

In [65]:
df.to_csv('Cleaned Bookstore Customer Analysis.csv')